// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;

import 'presentation/fav/data/fav_model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 6704196184882094328),
      name: 'FavoriteItem',
      lastPropertyId: const obx_int.IdUid(7, 3090982491147941541),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 4752173436741004817),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 7463874956189522665),
            name: 'itemId',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 1224988933493194202),
            name: 'itemType',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 1335167688585946445),
            name: 'title',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 1599780624895040946),
            name: 'description',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 5941786814532105218),
            name: 'imageUrl',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 3090982491147941541),
            name: 'addedDate',
            type: 10,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
obx.Store openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) {
  return obx.Store(getObjectBoxModel(),
      directory: directory,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(1, 6704196184882094328),
      lastIndexId: const obx_int.IdUid(0, 0),
      lastRelationId: const obx_int.IdUid(0, 0),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    FavoriteItem: obx_int.EntityDefinition<FavoriteItem>(
        model: _entities[0],
        toOneRelations: (FavoriteItem object) => [],
        toManyRelations: (FavoriteItem object) => {},
        getId: (FavoriteItem object) => object.id,
        setId: (FavoriteItem object, int id) {
          object.id = id;
        },
        objectToFB: (FavoriteItem object, fb.Builder fbb) {
          final itemTypeOffset = fbb.writeString(object.itemType);
          final titleOffset = fbb.writeString(object.title);
          final descriptionOffset = fbb.writeString(object.description);
          final imageUrlOffset = fbb.writeString(object.imageUrl);
          fbb.startTable(8);
          fbb.addInt64(0, object.id);
          fbb.addInt64(1, object.itemId);
          fbb.addOffset(2, itemTypeOffset);
          fbb.addOffset(3, titleOffset);
          fbb.addOffset(4, descriptionOffset);
          fbb.addOffset(5, imageUrlOffset);
          fbb.addInt64(6, object.addedDate.millisecondsSinceEpoch);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final itemIdParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0);
          final itemTypeParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final titleParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 10, '');
          final descriptionParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 12, '');
          final imageUrlParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 14, '');
          final object = FavoriteItem(
              id: idParam,
              itemId: itemIdParam,
              itemType: itemTypeParam,
              title: titleParam,
              description: descriptionParam,
              imageUrl: imageUrlParam)
            ..addedDate = DateTime.fromMillisecondsSinceEpoch(
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0));

          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [FavoriteItem] entity fields to define ObjectBox queries.
class FavoriteItem_ {
  /// See [FavoriteItem.id].
  static final id =
      obx.QueryIntegerProperty<FavoriteItem>(_entities[0].properties[0]);

  /// See [FavoriteItem.itemId].
  static final itemId =
      obx.QueryIntegerProperty<FavoriteItem>(_entities[0].properties[1]);

  /// See [FavoriteItem.itemType].
  static final itemType =
      obx.QueryStringProperty<FavoriteItem>(_entities[0].properties[2]);

  /// See [FavoriteItem.title].
  static final title =
      obx.QueryStringProperty<FavoriteItem>(_entities[0].properties[3]);

  /// See [FavoriteItem.description].
  static final description =
      obx.QueryStringProperty<FavoriteItem>(_entities[0].properties[4]);

  /// See [FavoriteItem.imageUrl].
  static final imageUrl =
      obx.QueryStringProperty<FavoriteItem>(_entities[0].properties[5]);

  /// See [FavoriteItem.addedDate].
  static final addedDate =
      obx.QueryDateProperty<FavoriteItem>(_entities[0].properties[6]);
}
